### ISSUE TITLE
Some Modifications

### ISSUE THREAD

**Issue by ChristophGaukel** [PBeGood4/mindcuber-python#1]
Hallo,

great, that you use package ev3_dc!

a few remarks about your code:

1) multiple Subclasses of EV3:
instead of:
turnn = ev3.Motor(ev3.PORT_B, protocol=ev3.USB, host='00:16:53:3D:F8:DF') 

do:
turnn = ev3.Motor(ev3.PORT_B, ev3_obj=rotate)

2) time control of motor movements (use move_to and move_by, e.g.):
instead of:
rotate.start_move_to(110, speed=20,brake=True)
        wait()

do:
rotate.move_to(110, speed=20,brake=True).start(thread=False)

Maybe you want to move both motors simultaniously, then do:
t1 = rotate.move_to(110, speed=20, brake=True)
t2 =  turnn.move_by(-310*dir, speed=60, brake=True)
t1.start()
t2.start(thread=False)
t1.join()  # wait if t1 lasts longer than t2

Kind regards,
Christoph

**Comment by Pedro-Beirao** [comment]
Hi
Using ev3_obj is much cleaner, thanks for that. 
I am pretty bad with threading, but as in my this program there is never a time where 2 motors move at once, I will change my code to:
```
movePlan = (
rotate.move_to(200, speed=20, brake=True) + etc
 )

movePlan.start(thread=False)
```

Thanks so much for this suggestions

This package is gold btw. Amazing job :)

**Comment by ChristophGaukel** [comment]
Hallo,

great, that your mindcuber works well, it's a good feeling, that you use my ev3_dc in your project. 

But I have bad news: my tests with hid on a windows machine failed. Reading returns empty messages. This says: pyusb and hid, both seem to fail on at least one system. May be, we can solve your problems on macOS. Give me a chance!

On Unix systems, the permissions of USB devices are handled very specific. I added this udev-rule on my ubuntu system as file /etc/udev/rules.d/90-legoev3.rules:

ATTRS{idVendor}=="0694",ATTRS{idProduct}=="0005",MODE="0666",GROUP="christoph"

This allows all members of group christoph (me allone), to read from and write to any mounted LEGO EV3 device. After adding or changing udev-rules, you need to reboot or run:

sudo udevadm control --reload

As far as I know, macOS is very close to Unix. Maybe, you can use pyusb together with libusb, when you add a udev-rule.
Can you please test it for me? I don't own a Mac.

Kind regards,
Christoph

**Comment by Pedro-Beirao** [comment]
Hi,

I was pretty sure hidapi would work in all OSs.

I tried everything to solve the pyusb problem on MacOS. Although Linux an mac are both Unix, mac doesnt have a udev file.

Is ti possible to have 2 different versions of ev3-dc? One for MacOS and Another for Windows/Linux?

Actually, a better idea is: on the ev3.py check what OS it is running on, and use pyusb / hidapi accordingly.

Regards
Pedro 


EDIT: there was an issue opened on the ev3-dc repo. It MIGHT solve the issue. (https://github.com/libusb/libusb/wiki/FAQ#How_can_I_run_libusb_applications_under_Mac_OS_X_if_there_is_already_a_kernel_extension_installed_for_the_device_and_claim_exclusive_access) this link might have some information about it. But I dont understand enough about kernel to try this.
